stages:
  stage_01:
    cmd: py stage_01.py
    deps:
      - stage_01.py
    outs:
      - artifact.txt

  stage_02:
    cmd: py stage_02.py
    deps:
      - artifact.txt
      - stage_02.py

  stage_03:
    cmd: py stage_03.py
    deps:
      - artifact.txt
      - stage_03.py